<?php

use PHPUnit\Framework\TestCase;

/**
 * Unit tests for PostgreSQL CREATE TABLE translation.
 */
class WP_PostgreSQL_Create_Table_Translator_Tests extends TestCase {
	/**
	 * Tests a WordPress options table CREATE statement.
	 */
	public function test_translate_wp_options_create_table(): void {
		$this->assertSame(
			array(
				"CREATE TABLE \"wp_options\" (\n  \"option_id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  \"option_name\" varchar(191) NOT NULL DEFAULT '',\n  \"option_value\" text NOT NULL,\n  \"autoload\" varchar(20) NOT NULL DEFAULT 'yes',\n  PRIMARY KEY (\"option_id\")\n)",
				'CREATE UNIQUE INDEX "wp_options__option_name" ON "wp_options" ("option_name")',
				'CREATE INDEX "wp_options__autoload" ON "wp_options" ("autoload")',
			),
			$this->translate(
				"CREATE TABLE wp_options (
					option_id bigint(20) unsigned NOT NULL auto_increment,
					option_name varchar(191) NOT NULL default '',
					option_value longtext NOT NULL,
					autoload varchar(20) NOT NULL default 'yes',
					PRIMARY KEY (option_id),
					UNIQUE KEY option_name (option_name),
					KEY autoload (autoload)
				) DEFAULT CHARACTER SET utf8mb4"
			)
		);
	}

	/**
	 * Tests a compound primary key and secondary index.
	 */
	public function test_translate_wp_term_relationships_create_table(): void {
		$this->assertSame(
			array(
				"CREATE TABLE \"wp_term_relationships\" (\n  \"object_id\" bigint NOT NULL DEFAULT '0',\n  \"term_taxonomy_id\" bigint NOT NULL DEFAULT '0',\n  \"term_order\" integer NOT NULL DEFAULT '0',\n  PRIMARY KEY (\"object_id\", \"term_taxonomy_id\")\n)",
				'CREATE INDEX "wp_term_relationships__term_taxonomy_id" ON "wp_term_relationships" ("term_taxonomy_id")',
			),
			$this->translate(
				'CREATE TABLE wp_term_relationships (
					object_id bigint(20) unsigned NOT NULL default 0,
					term_taxonomy_id bigint(20) unsigned NOT NULL default 0,
					term_order int(11) NOT NULL default 0,
					PRIMARY KEY (object_id,term_taxonomy_id),
					KEY term_taxonomy_id (term_taxonomy_id)
				) DEFAULT CHARACTER SET utf8mb4'
			)
		);
	}

	/**
	 * Tests WordPress schema identifiers that are tokenized as MySQL keywords.
	 */
	public function test_translate_wordpress_keyword_identifier_columns(): void {
		$this->assertSame(
			array(
				"CREATE TABLE \"wp_keyword_identifiers\" (\n  \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  \"name\" varchar(200) NOT NULL DEFAULT '',\n  \"description\" text NOT NULL,\n  PRIMARY KEY (\"id\")\n)",
				'CREATE INDEX "wp_keyword_identifiers__name" ON "wp_keyword_identifiers" ("name")',
				'CREATE INDEX "wp_keyword_identifiers__description" ON "wp_keyword_identifiers" ("description")',
			),
			$this->translate(
				"CREATE TABLE wp_keyword_identifiers (
					id bigint(20) unsigned NOT NULL auto_increment,
					name varchar(200) NOT NULL default '',
					description longtext NOT NULL,
					PRIMARY KEY (id),
					KEY name (name(191)),
					KEY description (description(191))
				) DEFAULT CHARACTER SET utf8mb4"
			)
		);
	}

	/**
	 * Tests MySQL prefix index lengths are stripped from PostgreSQL index columns.
	 */
	public function test_translate_strips_prefix_index_lengths(): void {
		$this->assertSame(
			array(
				"CREATE TABLE \"wp_postmeta\" (\n  \"meta_id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  \"meta_key\" varchar(255) DEFAULT NULL,\n  PRIMARY KEY (\"meta_id\")\n)",
				'CREATE INDEX "wp_postmeta__meta_key" ON "wp_postmeta" ("meta_key")',
			),
			$this->translate(
				'CREATE TABLE wp_postmeta (
					meta_id bigint(20) unsigned NOT NULL auto_increment,
					meta_key varchar(255) default NULL,
					PRIMARY KEY (meta_id),
					KEY meta_key (meta_key(191))
				) DEFAULT CHARACTER SET utf8mb4'
			)
		);
	}

	/**
	 * Tests supported MySQL BTREE index options are ignored for PostgreSQL DDL.
	 */
	public function test_translate_ignores_supported_btree_index_options(): void {
		$sql = 'CREATE TABLE wp_index_options (
			id int NOT NULL,
			value varchar(255) NOT NULL,
			KEY value_lookup USING BTREE (value) KEY_BLOCK_SIZE=8 INVISIBLE COMMENT "Lookup",
			UNIQUE KEY id_lookup (id) VISIBLE
		) DEFAULT CHARACTER SET utf8mb4';

		$translator = new WP_PostgreSQL_Create_Table_Translator();

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_index_options\" (\n  \"id\" integer NOT NULL,\n  \"value\" varchar(255) NOT NULL\n)",
				'CREATE INDEX "wp_index_options__value_lookup" ON "wp_index_options" ("value")',
				'CREATE UNIQUE INDEX "wp_index_options__id_lookup" ON "wp_index_options" ("id")',
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );
		$this->assertSame(
			array( 'value_lookup', 'id_lookup' ),
			array_column( $metadata[0]['indexes'], 'name' )
		);
	}

	/**
	 * Tests unsupported MySQL index options fail explicitly.
	 */
	public function test_translate_rejects_unsupported_index_options(): void {
		$queries = array(
			'CREATE TABLE wp_bad_index_option (id int, value varchar(255), KEY value_lookup USING HASH (value))',
			'CREATE TABLE wp_bad_index_option (id int, body text, FULLTEXT KEY body_fulltext (body) WITH PARSER ngram)',
			'CREATE TABLE wp_bad_index_option (id int, shape point, SPATIAL KEY shape_spatial (shape) KEY_BLOCK_SIZE=8)',
			'CREATE TABLE wp_bad_index_option (id int, PRIMARY KEY (id) INVISIBLE)',
		);

		foreach ( $queries as $query ) {
			$translator = new WP_PostgreSQL_Create_Table_Translator();

			try {
				$translator->translate_schema( $query );
				$this->fail( 'Expected unsupported CREATE TABLE index option to throw.' );
			} catch ( InvalidArgumentException $exception ) {
				$this->assertSame( 'Unsupported CREATE TABLE index option.', $exception->getMessage(), $query );
			}
		}
	}

	/**
	 * Tests zero date defaults are translated as text while MySQL metadata is preserved.
	 */
	public function test_translate_zero_date_defaults_as_text_and_metadata_defaults(): void {
		$sql = "CREATE TABLE wp_zero_dates (
			id bigint(20) unsigned NOT NULL auto_increment,
			created_date date NOT NULL DEFAULT '0000-00-00',
			created_at datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
			updated_at timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
			PRIMARY KEY (id)
		) DEFAULT CHARACTER SET utf8mb4";

		$translator = new WP_PostgreSQL_Create_Table_Translator();

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_zero_dates\" (\n  \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  \"created_date\" text NOT NULL DEFAULT '0000-00-00',\n  \"created_at\" text NOT NULL DEFAULT '0000-00-00 00:00:00',\n  \"updated_at\" text NOT NULL DEFAULT '0000-00-00 00:00:00',\n  PRIMARY KEY (\"id\")\n)",
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );

		$this->assertSame(
			array( 'date', 'datetime', 'timestamp' ),
			array_column( array_slice( $metadata[0]['columns'], 1 ), 'type' )
		);
		$this->assertSame(
			array( '0000-00-00', '0000-00-00 00:00:00', '0000-00-00 00:00:00' ),
			array_column( array_slice( $metadata[0]['columns'], 1 ), 'default' )
		);
	}

	/**
	 * Tests FULLTEXT and SPATIAL indexes are metadata-only in PostgreSQL DDL.
	 */
	public function test_translate_fulltext_and_spatial_indexes_as_metadata_only(): void {
		$sql = 'CREATE TABLE wp_search_geo (
			id bigint(20) unsigned NOT NULL,
			body longtext NOT NULL,
			shape point NOT NULL,
			PRIMARY KEY (id),
			FULLTEXT KEY body_fulltext (body),
			SPATIAL KEY shape_spatial (shape),
			KEY id_lookup (id)
		) DEFAULT CHARACTER SET utf8mb4';

		$translator = new WP_PostgreSQL_Create_Table_Translator();

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_search_geo\" (\n  \"id\" bigint NOT NULL,\n  \"body\" text NOT NULL,\n  \"shape\" text NOT NULL,\n  PRIMARY KEY (\"id\")\n)",
				'CREATE INDEX "wp_search_geo__id_lookup" ON "wp_search_geo" ("id")',
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );
		$this->assertSame(
			array( 'PRIMARY', 'body_fulltext', 'shape_spatial', 'id_lookup' ),
			array_column( $metadata[0]['indexes'], 'name' )
		);
		$this->assertSame(
			array( 'BTREE', 'FULLTEXT', 'SPATIAL', 'BTREE' ),
			array_column( $metadata[0]['indexes'], 'index_type' )
		);
		$this->assertNull( $metadata[0]['indexes'][1]['columns'][0]['sub_part'] );
		$this->assertSame( 32, $metadata[0]['indexes'][2]['columns'][0]['sub_part'] );
	}

	/**
	 * Tests temporary IF NOT EXISTS statements.
	 */
	public function test_translate_temporary_if_not_exists(): void {
		$this->assertSame(
			array(
				"CREATE TEMPORARY TABLE IF NOT EXISTS \"wp_tmp\" (\n  \"id\" integer NOT NULL,\n  PRIMARY KEY (\"id\")\n)",
				'CREATE INDEX IF NOT EXISTS "wp_tmp__id_idx" ON "wp_tmp" ("id")',
			),
			$this->translate(
				'CREATE TEMPORARY TABLE IF NOT EXISTS wp_tmp (
					id int(11) NOT NULL,
					PRIMARY KEY (id),
					KEY id_idx (id)
				) DEFAULT CHARACTER SET utf8mb4'
			)
		);
	}

	/**
	 * Tests MySQL charset metadata is extracted from CREATE TABLE statements.
	 */
	public function test_extract_schema_metadata_preserves_mysql_charsets(): void {
		$translator = new WP_PostgreSQL_Create_Table_Translator();

		$this->assertSame(
			array(
				array(
					'table_name' => 'wp_charset_test',
					'columns'    => array(
						array(
							'name'      => 'a',
							'type'      => 'varchar(50)',
							'charset'   => 'latin1',
							'collation' => 'latin1_swedish_ci',
							'ordinal'   => 1,
						),
						array(
							'name'      => 'b',
							'type'      => 'text',
							'charset'   => 'koi8r',
							'collation' => 'koi8r_general_ci',
							'ordinal'   => 2,
						),
						array(
							'name'      => 'c',
							'type'      => 'binary',
							'charset'   => null,
							'collation' => null,
							'ordinal'   => 3,
						),
						array(
							'name'      => 'd',
							'type'      => 'int',
							'charset'   => null,
							'collation' => null,
							'ordinal'   => 4,
						),
					),
				),
			),
			$translator->extract_schema_metadata(
				'CREATE TABLE wp_charset_test (
					a VARCHAR(50) CHARACTER SET latin1,
					b TEXT COLLATE koi8r_general_ci,
					c BINARY,
					d INT
				) DEFAULT CHARSET utf8mb3'
			)
		);
	}

	/**
	 * Tests numeric precision and scale are preserved in DDL and metadata.
	 */
	public function test_numeric_precision_and_scale_are_preserved(): void {
		$translator = new WP_PostgreSQL_Create_Table_Translator();
		$sql        = 'CREATE TABLE wp_numeric_test (
			amount DECIMAL(10,2) NOT NULL,
			ratio NUMERIC(12,6),
			score FLOAT(10,3),
			measure DOUBLE(8,4)
		)';

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_numeric_test\" (\n  \"amount\" numeric(10,2) NOT NULL,\n  \"ratio\" numeric(12,6),\n  \"score\" numeric(10,3),\n  \"measure\" numeric(8,4)\n)",
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql );

		$this->assertSame( 'decimal(10,2)', $metadata[0]['columns'][0]['type'] );
		$this->assertSame( 'numeric(12,6)', $metadata[0]['columns'][1]['type'] );
		$this->assertSame( 'float(10,3)', $metadata[0]['columns'][2]['type'] );
		$this->assertSame( 'double(8,4)', $metadata[0]['columns'][3]['type'] );
	}

	/**
	 * Tests unsupported CREATE TABLE ... SELECT statements are rejected.
	 */
	public function test_translate_rejects_create_table_as_select(): void {
		$this->expectException( InvalidArgumentException::class );
		$this->translate( 'CREATE TABLE wp_copy AS SELECT 1 AS id' );
	}

	/**
	 * Translates MySQL CREATE TABLE SQL.
	 *
	 * @param string $sql MySQL CREATE TABLE statement.
	 * @return string[] PostgreSQL DDL statements.
	 */
	private function translate( string $sql ): array {
		$translator = new WP_PostgreSQL_Create_Table_Translator();
		return $translator->translate_schema( $sql );
	}
}
