<?php

use PHPUnit\Framework\TestCase;

/**
 * Unit tests for PostgreSQL CREATE TABLE translation.
 */
class WP_PostgreSQL_Create_Table_Translator_Tests extends TestCase {
	/**
	 * Tests a WordPress options table CREATE statement.
	 */
	public function test_translate_wp_options_create_table(): void {
		$this->assertSame(
			array(
				"CREATE TABLE \"wp_options\" (\n  \"option_id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  \"option_name\" varchar(191) NOT NULL DEFAULT '',\n  \"option_value\" text NOT NULL,\n  \"autoload\" varchar(20) NOT NULL DEFAULT 'yes',\n  PRIMARY KEY (\"option_id\")\n)",
				'CREATE UNIQUE INDEX "wp_options__option_name" ON "wp_options" ("option_name")',
				'CREATE INDEX "wp_options__autoload" ON "wp_options" ("autoload")',
			),
			$this->translate(
				"CREATE TABLE wp_options (
					option_id bigint(20) unsigned NOT NULL auto_increment,
					option_name varchar(191) NOT NULL default '',
					option_value longtext NOT NULL,
					autoload varchar(20) NOT NULL default 'yes',
					PRIMARY KEY (option_id),
					UNIQUE KEY option_name (option_name),
					KEY autoload (autoload)
				) DEFAULT CHARACTER SET utf8mb4"
			)
		);
	}

	/**
	 * Tests a compound primary key and secondary index.
	 */
	public function test_translate_wp_term_relationships_create_table(): void {
		$this->assertSame(
			array(
				"CREATE TABLE \"wp_term_relationships\" (\n  \"object_id\" bigint NOT NULL DEFAULT '0',\n  \"term_taxonomy_id\" bigint NOT NULL DEFAULT '0',\n  \"term_order\" integer NOT NULL DEFAULT '0',\n  PRIMARY KEY (\"object_id\", \"term_taxonomy_id\")\n)",
				'CREATE INDEX "wp_term_relationships__term_taxonomy_id" ON "wp_term_relationships" ("term_taxonomy_id")',
			),
			$this->translate(
				'CREATE TABLE wp_term_relationships (
					object_id bigint(20) unsigned NOT NULL default 0,
					term_taxonomy_id bigint(20) unsigned NOT NULL default 0,
					term_order int(11) NOT NULL default 0,
					PRIMARY KEY (object_id,term_taxonomy_id),
					KEY term_taxonomy_id (term_taxonomy_id)
				) DEFAULT CHARACTER SET utf8mb4'
			)
		);
	}

	/**
	 * Tests MySQL prefix index lengths are stripped from PostgreSQL index columns.
	 */
	public function test_translate_strips_prefix_index_lengths(): void {
		$this->assertSame(
			array(
				"CREATE TABLE \"wp_postmeta\" (\n  \"meta_id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  \"meta_key\" varchar(255) DEFAULT NULL,\n  PRIMARY KEY (\"meta_id\")\n)",
				'CREATE INDEX "wp_postmeta__meta_key" ON "wp_postmeta" ("meta_key")',
			),
			$this->translate(
				'CREATE TABLE wp_postmeta (
					meta_id bigint(20) unsigned NOT NULL auto_increment,
					meta_key varchar(255) default NULL,
					PRIMARY KEY (meta_id),
					KEY meta_key (meta_key(191))
				) DEFAULT CHARACTER SET utf8mb4'
			)
		);
	}

	/**
	 * Tests temporary IF NOT EXISTS statements.
	 */
	public function test_translate_temporary_if_not_exists(): void {
		$this->assertSame(
			array(
				"CREATE TEMPORARY TABLE IF NOT EXISTS \"wp_tmp\" (\n  \"id\" integer NOT NULL,\n  PRIMARY KEY (\"id\")\n)",
				'CREATE INDEX IF NOT EXISTS "wp_tmp__id_idx" ON "wp_tmp" ("id")',
			),
			$this->translate(
				'CREATE TEMPORARY TABLE IF NOT EXISTS wp_tmp (
					id int(11) NOT NULL,
					PRIMARY KEY (id),
					KEY id_idx (id)
				) DEFAULT CHARACTER SET utf8mb4'
			)
		);
	}

	/**
	 * Tests unsupported CREATE TABLE ... SELECT statements are rejected.
	 */
	public function test_translate_rejects_create_table_as_select(): void {
		$this->expectException( InvalidArgumentException::class );
		$this->translate( 'CREATE TABLE wp_copy AS SELECT 1 AS id' );
	}

	/**
	 * Translates MySQL CREATE TABLE SQL.
	 *
	 * @param string $sql MySQL CREATE TABLE statement.
	 * @return string[] PostgreSQL DDL statements.
	 */
	private function translate( string $sql ): array {
		$translator = new WP_PostgreSQL_Create_Table_Translator();
		return $translator->translate_schema( $sql );
	}
}
