<?php

use PHPUnit\Framework\TestCase;

/**
 * Unit tests for PostgreSQL CREATE TABLE translation.
 */
class WP_PostgreSQL_Create_Table_Translator_Tests extends TestCase {
	/**
	 * Tests a WordPress options table CREATE statement.
	 */
	public function test_translate_wp_options_create_table(): void {
		$this->assertSame(
			array(
				"CREATE TABLE \"wp_options\" (\n  \"option_id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  \"option_name\" varchar(191) NOT NULL DEFAULT '',\n  \"option_value\" __wp_mysql_longtext NOT NULL,\n  \"autoload\" varchar(20) NOT NULL DEFAULT 'yes',\n  PRIMARY KEY (\"option_id\")\n)",
				'CREATE UNIQUE INDEX "wp_options__option_name" ON "wp_options" ("option_name")',
				'CREATE INDEX "wp_options__autoload" ON "wp_options" ("autoload")',
			),
			$this->translate(
				"CREATE TABLE wp_options (
						option_id bigint(20) unsigned NOT NULL auto_increment,
						option_name varchar(191) NOT NULL default '',
						option_value longtext NOT NULL,
						autoload varchar(20) NOT NULL default 'yes',
						PRIMARY KEY (option_id),
						UNIQUE KEY option_name (option_name),
						KEY autoload (autoload)
					) DEFAULT CHARACTER SET utf8mb4"
			)
		);
	}

	/**
	 * Tests original CREATE TABLE statements are extracted for driver-owned install DDL.
	 */
	public function test_extract_create_table_statements_preserves_original_create_sql(): void {
		$sql        = "CREATE TABLE wp_options (
				option_id bigint(20) unsigned NOT NULL auto_increment,
				option_name varchar(191) NOT NULL default '',
				PRIMARY KEY (option_id)
			) DEFAULT CHARACTER SET utf8mb4;
			SELECT 1;
				CREATE TABLE wp_posts (
					ID bigint(20) unsigned NOT NULL auto_increment,
					post_title text NOT NULL,
					PRIMARY KEY (ID)
				) DEFAULT CHARACTER SET utf8mb4;";
		$translator = new WP_PostgreSQL_Create_Table_Translator();
		$statements = $translator->extract_create_table_statements( $sql );

		$this->assertCount( 2, $statements );
		$this->assertStringStartsWith( 'CREATE TABLE wp_options', $statements[0] );
		$this->assertStringContainsString( 'PRIMARY KEY (option_id)', $statements[0] );
		$this->assertStringNotContainsString( 'SELECT 1', implode( "\n", $statements ) );
		$this->assertStringNotContainsString( ';', implode( "\n", $statements ) );
		$this->assertStringStartsWith( 'CREATE TABLE wp_posts', $statements[1] );
		$this->assertStringContainsString( 'PRIMARY KEY (ID)', $statements[1] );
	}

	/**
	 * Tests a compound primary key and secondary index.
	 */
	public function test_translate_wp_term_relationships_create_table(): void {
		$this->assertSame(
			array(
				"CREATE TABLE \"wp_term_relationships\" (\n  \"object_id\" __wp_mysql_bigint_20_unsigned NOT NULL DEFAULT '0',\n  \"term_taxonomy_id\" __wp_mysql_bigint_20_unsigned NOT NULL DEFAULT '0',\n  \"term_order\" __wp_mysql_int_11 NOT NULL DEFAULT '0',\n  PRIMARY KEY (\"object_id\", \"term_taxonomy_id\")\n)",
				'CREATE INDEX "wp_term_relationships__term_taxonomy_id" ON "wp_term_relationships" ("term_taxonomy_id")',
			),
			$this->translate(
				'CREATE TABLE wp_term_relationships (
					object_id bigint(20) unsigned NOT NULL default 0,
					term_taxonomy_id bigint(20) unsigned NOT NULL default 0,
					term_order int(11) NOT NULL default 0,
					PRIMARY KEY (object_id,term_taxonomy_id),
					KEY term_taxonomy_id (term_taxonomy_id)
				) DEFAULT CHARACTER SET utf8mb4'
			)
		);
	}

	/**
	 * Tests MySQL integer aliases are translated while preserving their metadata shape.
	 */
	public function test_translate_integer_aliases_create_table(): void {
		$sql        = 'CREATE TABLE wp_integer_aliases (
			tiny_value int1,
			small_value int2,
			medium_value int3,
			regular_value int4 unsigned,
			huge_value int8,
			next_id int4 NOT NULL AUTO_INCREMENT,
			PRIMARY KEY (next_id)
		)';
		$translator = new WP_PostgreSQL_Create_Table_Translator();

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_integer_aliases\" (\n  \"tiny_value\" __wp_mysql_int1,\n  \"small_value\" __wp_mysql_int2,\n  \"medium_value\" __wp_mysql_int3,\n  \"regular_value\" __wp_mysql_int4_unsigned,\n  \"huge_value\" __wp_mysql_int8,\n  \"next_id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  PRIMARY KEY (\"next_id\")\n)",
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );

		$this->assertSame(
			array( 'int1', 'int2', 'int3', 'int4 unsigned', 'int8', 'int4' ),
			array_column( $metadata[0]['columns'], 'type' )
		);
		$this->assertSame( 'auto_increment', $metadata[0]['columns'][5]['extra'] );
	}

	/**
	 * Tests WordPress schema identifiers that are tokenized as MySQL keywords.
	 */
	public function test_translate_wordpress_keyword_identifier_columns(): void {
		$this->assertSame(
			array(
				"CREATE TABLE \"wp_keyword_identifiers\" (\n  \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  \"name\" varchar(200) NOT NULL DEFAULT '',\n  \"description\" __wp_mysql_longtext NOT NULL,\n  PRIMARY KEY (\"id\")\n)",
				'CREATE INDEX "wp_keyword_identifiers__name" ON "wp_keyword_identifiers" (SUBSTR(CAST("name" AS text), 1, 191))',
				'CREATE INDEX "wp_keyword_identifiers__description" ON "wp_keyword_identifiers" (SUBSTR(CAST("description" AS text), 1, 191))',
			),
			$this->translate(
				"CREATE TABLE wp_keyword_identifiers (
					id bigint(20) unsigned NOT NULL auto_increment,
					name varchar(200) NOT NULL default '',
					description longtext NOT NULL,
					PRIMARY KEY (id),
					KEY name (name(191)),
					KEY description (description(191))
				) DEFAULT CHARACTER SET utf8mb4"
			)
		);
	}

	/**
	 * Tests MySQL prefix index lengths become PostgreSQL expression indexes.
	 */
	public function test_translate_prefix_index_lengths_as_expression_indexes(): void {
		$this->assertSame(
			array(
				"CREATE TABLE \"wp_postmeta\" (\n  \"meta_id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  \"meta_key\" varchar(255) DEFAULT NULL,\n  PRIMARY KEY (\"meta_id\")\n)",
				'CREATE INDEX "wp_postmeta__meta_key" ON "wp_postmeta" (SUBSTR(CAST("meta_key" AS text), 1, 191))',
			),
			$this->translate(
				'CREATE TABLE wp_postmeta (
					meta_id bigint(20) unsigned NOT NULL auto_increment,
					meta_key varchar(255) default NULL,
					PRIMARY KEY (meta_id),
					KEY meta_key (meta_key(191))
				) DEFAULT CHARACTER SET utf8mb4'
			)
		);
	}

	/**
	 * Tests unique MySQL prefix indexes become PostgreSQL expression indexes.
	 */
	public function test_translate_unique_prefix_index_lengths_as_expression_indexes(): void {
		$sql = 'CREATE TABLE wp_prefix_unique (
			id bigint(20) unsigned NOT NULL auto_increment,
			slug varchar(255) NOT NULL,
			PRIMARY KEY (id),
			UNIQUE KEY slug_prefix (slug(10))
		) DEFAULT CHARACTER SET utf8mb4';

		$translator = new WP_PostgreSQL_Create_Table_Translator();

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_prefix_unique\" (\n  \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  \"slug\" varchar(255) NOT NULL,\n  PRIMARY KEY (\"id\")\n)",
				'CREATE UNIQUE INDEX "wp_prefix_unique__slug_prefix" ON "wp_prefix_unique" (SUBSTR(CAST("slug" AS text), 1, 10))',
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );
		$this->assertSame( '10', (string) $metadata[0]['indexes'][1]['columns'][0]['sub_part'] );
	}

	/**
	 * Tests MySQL key part directions are preserved in secondary index DDL and metadata.
	 */
	public function test_translate_preserves_secondary_index_directions(): void {
		$sql = 'CREATE TABLE wp_directional_indexes (
			id bigint(20) unsigned NOT NULL auto_increment,
			score int NOT NULL,
			name varchar(255) NOT NULL,
			created_at datetime NOT NULL,
			PRIMARY KEY (id),
			KEY score_name (score ASC, name(16) DESC, created_at DESC)
		) DEFAULT CHARACTER SET utf8mb4';

		$translator = new WP_PostgreSQL_Create_Table_Translator();

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_directional_indexes\" (\n  \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  \"score\" integer NOT NULL,\n  \"name\" varchar(255) NOT NULL,\n  \"created_at\" __wp_mysql_datetime NOT NULL,\n  PRIMARY KEY (\"id\")\n)",
				'CREATE INDEX "wp_directional_indexes__score_name" ON "wp_directional_indexes" ("score" ASC, SUBSTR(CAST("name" AS text), 1, 16) DESC, "created_at" DESC)',
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );
		$this->assertSame(
			array( 'A', 'D', 'D' ),
			array_column( $metadata[0]['indexes'][1]['columns'], 'collation' )
		);
		$this->assertSame(
			array( null, 16, null ),
			array_column( $metadata[0]['indexes'][1]['columns'], 'sub_part' )
		);
	}

	/**
	 * Tests supported MySQL BTREE index options are ignored for PostgreSQL DDL.
	 */
	public function test_translate_ignores_supported_btree_index_options(): void {
		$sql = 'CREATE TABLE wp_index_options (
			id int NOT NULL,
			value varchar(255) NOT NULL,
			KEY value_lookup USING BTREE (value) KEY_BLOCK_SIZE=8 INVISIBLE COMMENT "Lookup",
			UNIQUE KEY id_lookup (id) VISIBLE
		) DEFAULT CHARACTER SET utf8mb4';

		$translator = new WP_PostgreSQL_Create_Table_Translator();

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_index_options\" (\n  \"id\" integer NOT NULL,\n  \"value\" varchar(255) NOT NULL\n)",
				'CREATE INDEX "wp_index_options__value_lookup" ON "wp_index_options" (SUBSTR(CAST("value" AS text), 1, 191))',
				'CREATE UNIQUE INDEX "wp_index_options__id_lookup" ON "wp_index_options" ("id")',
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );
		$this->assertSame(
			array( 'value_lookup', 'id_lookup' ),
			array_column( $metadata[0]['indexes'], 'name' )
		);
	}

	/**
	 * Tests inline column constraints are translated and preserved in metadata.
	 */
	public function test_translate_inline_column_constraints_and_metadata(): void {
		$sql = 'CREATE TABLE wp_inline_constraints (
			id bigint(20) unsigned NOT NULL auto_increment PRIMARY KEY,
			slug varchar(100) UNIQUE,
			parent_id bigint(20) unsigned REFERENCES wp_inline_parent(id) ON DELETE CASCADE ON UPDATE SET NULL
		) DEFAULT CHARACTER SET utf8mb4';

		$translator = new WP_PostgreSQL_Create_Table_Translator();

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_inline_constraints\" (\n  \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,\n  \"slug\" varchar(100) CONSTRAINT \"slug\" UNIQUE,\n  \"parent_id\" __wp_mysql_bigint_20_unsigned CONSTRAINT \"wp_inline_constraints_ibfk_1\" REFERENCES \"wp_inline_parent\" (\"id\") ON DELETE CASCADE ON UPDATE SET NULL\n)",
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );

		$this->assertSame(
			array( 'PRIMARY', 'slug' ),
			array_column( $metadata[0]['indexes'], 'name' )
		);
		$this->assertSame(
			array(
				array(
					'name'               => 'wp_inline_constraints_ibfk_1',
					'columns'            => array( 'parent_id' ),
					'referenced_schema'  => null,
					'referenced_table'   => 'wp_inline_parent',
					'referenced_columns' => array( 'id' ),
					'update_rule'        => 'SET NULL',
					'delete_rule'        => 'CASCADE',
				),
			),
			$metadata[0]['foreign_keys']
		);
		$this->assertSame( 'NO', $metadata[0]['columns'][0]['nullable'] );
	}

	/**
	 * Tests table-level foreign keys are translated and preserved in metadata.
	 */
	public function test_translate_table_level_foreign_keys_and_metadata(): void {
		$sql = 'CREATE TABLE wp_table_foreign_keys (
			id int NOT NULL,
			parent_id int NOT NULL,
			parent_site_id int NOT NULL,
			parent_extra_id int NOT NULL,
			CONSTRAINT fk_parent FOREIGN KEY parent_lookup (parent_id, parent_site_id) REFERENCES wp_parent (id, site_id) ON DELETE CASCADE ON UPDATE RESTRICT,
			CONSTRAINT wp_table_foreign_keys_ibfk_1 FOREIGN KEY (parent_extra_id) REFERENCES wp_parent (id),
			FOREIGN KEY (parent_id) REFERENCES wp_parent (id)
		) DEFAULT CHARACTER SET utf8mb4';

		$translator = new WP_PostgreSQL_Create_Table_Translator();

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_table_foreign_keys\" (\n  \"id\" integer NOT NULL,\n  \"parent_id\" integer NOT NULL,\n  \"parent_site_id\" integer NOT NULL,\n  \"parent_extra_id\" integer NOT NULL,\n  CONSTRAINT \"fk_parent\" FOREIGN KEY (\"parent_id\", \"parent_site_id\") REFERENCES \"wp_parent\" (\"id\", \"site_id\") ON DELETE CASCADE ON UPDATE RESTRICT,\n  CONSTRAINT \"wp_table_foreign_keys_ibfk_1\" FOREIGN KEY (\"parent_extra_id\") REFERENCES \"wp_parent\" (\"id\"),\n  CONSTRAINT \"wp_table_foreign_keys_ibfk_2\" FOREIGN KEY (\"parent_id\") REFERENCES \"wp_parent\" (\"id\")\n)",
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );
		$this->assertSame(
			array(
				array(
					'name'               => 'fk_parent',
					'columns'            => array( 'parent_id', 'parent_site_id' ),
					'referenced_schema'  => null,
					'referenced_table'   => 'wp_parent',
					'referenced_columns' => array( 'id', 'site_id' ),
					'update_rule'        => 'RESTRICT',
					'delete_rule'        => 'CASCADE',
				),
				array(
					'name'               => 'wp_table_foreign_keys_ibfk_1',
					'columns'            => array( 'parent_extra_id' ),
					'referenced_schema'  => null,
					'referenced_table'   => 'wp_parent',
					'referenced_columns' => array( 'id' ),
					'update_rule'        => 'NO ACTION',
					'delete_rule'        => 'NO ACTION',
				),
				array(
					'name'               => 'wp_table_foreign_keys_ibfk_2',
					'columns'            => array( 'parent_id' ),
					'referenced_schema'  => null,
					'referenced_table'   => 'wp_parent',
					'referenced_columns' => array( 'id' ),
					'update_rule'        => 'NO ACTION',
					'delete_rule'        => 'NO ACTION',
				),
			),
			$metadata[0]['foreign_keys']
		);
	}

	/**
	 * Tests unsupported MySQL index options fail explicitly.
	 */
	public function test_translate_rejects_unsupported_index_options(): void {
		$queries = array(
			'CREATE TABLE wp_bad_index_option (id int, body text, FULLTEXT KEY body_fulltext (body) WITH PARSER ngram)',
			'CREATE TABLE wp_bad_index_option (id int, shape point, SPATIAL KEY shape_spatial (shape) KEY_BLOCK_SIZE=8)',
			'CREATE TABLE wp_bad_index_option (id int, PRIMARY KEY (id) INVISIBLE)',
		);

		foreach ( $queries as $query ) {
			$translator = new WP_PostgreSQL_Create_Table_Translator();

			try {
				$translator->translate_schema( $query );
				$this->fail( 'Expected unsupported CREATE TABLE index option to throw.' );
			} catch ( InvalidArgumentException $exception ) {
				$this->assertSame( 'Unsupported CREATE TABLE index option.', $exception->getMessage(), $query );
			}
		}
	}

	/**
	 * Tests HASH index declarations are normalized to BTREE like the SQLite backend.
	 */
	public function test_translate_accepts_hash_indexes_as_btree(): void {
		$sql = 'CREATE TABLE wp_hash_index (
			id int,
			value varchar(255),
			slug varchar(191),
			KEY value_lookup USING HASH (value),
			UNIQUE KEY slug_lookup (slug) USING HASH
		)';

		$translator = new WP_PostgreSQL_Create_Table_Translator();

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_hash_index\" (\n  \"id\" integer,\n  \"value\" varchar(255),\n  \"slug\" varchar(191)\n)",
				'CREATE INDEX "wp_hash_index__value_lookup" ON "wp_hash_index" (SUBSTR(CAST("value" AS text), 1, 191))',
				'CREATE UNIQUE INDEX "wp_hash_index__slug_lookup" ON "wp_hash_index" ("slug")',
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );
		$this->assertSame(
			array( 'value_lookup', 'slug_lookup' ),
			array_column( $metadata[0]['indexes'], 'name' )
		);
		$this->assertSame(
			array( 'BTREE', 'BTREE' ),
			array_column( $metadata[0]['indexes'], 'index_type' )
		);
	}

	/**
	 * Tests unsupported MySQL column attributes fail explicitly.
	 */
	public function test_translate_rejects_unsupported_column_attributes(): void {
		$queries = array(
			'CREATE TABLE wp_bad_column_attribute (base int, generated_value int GENERATED ALWAYS AS (base + 1) STORED)',
			'CREATE TABLE wp_bad_column_attribute (base int, generated_value int GENERATED ALWAYS AS (base + 1) VIRTUAL)',
			'CREATE TABLE wp_bad_column_attribute (id int INVISIBLE)',
			'CREATE TABLE wp_bad_column_attribute (id int VISIBLE)',
			'CREATE TABLE wp_bad_column_attribute (id int COLUMN_FORMAT FIXED)',
			'CREATE TABLE wp_bad_column_attribute (id int STORAGE DISK)',
		);

		foreach ( $queries as $query ) {
			$translator = new WP_PostgreSQL_Create_Table_Translator();

			try {
				$translator->translate_schema( $query );
				$this->fail( 'Expected unsupported CREATE TABLE column attribute to throw.' );
			} catch ( InvalidArgumentException $exception ) {
				$this->assertSame( 'Unsupported CREATE TABLE column attribute.', $exception->getMessage(), $query );
			}
		}
	}

	/**
	 * Tests zero date defaults are translated as text while MySQL metadata is preserved.
	 */
	public function test_translate_zero_date_defaults_as_text_and_metadata_defaults(): void {
		$sql = "CREATE TABLE wp_zero_dates (
			id bigint(20) unsigned NOT NULL auto_increment,
			created_date date NOT NULL DEFAULT '0000-00-00',
			created_at datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
			updated_at timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
			PRIMARY KEY (id)
		) DEFAULT CHARACTER SET utf8mb4";

		$translator = new WP_PostgreSQL_Create_Table_Translator();

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_zero_dates\" (\n  \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  \"created_date\" __wp_mysql_date NOT NULL DEFAULT '0000-00-00',\n  \"created_at\" __wp_mysql_datetime NOT NULL DEFAULT '0000-00-00 00:00:00',\n  \"updated_at\" __wp_mysql_timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',\n  PRIMARY KEY (\"id\")\n)",
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );

		$this->assertSame(
			array( 'date', 'datetime', 'timestamp' ),
			array_column( array_slice( $metadata[0]['columns'], 1 ), 'type' )
		);
		$this->assertSame(
			array( '0000-00-00', '0000-00-00 00:00:00', '0000-00-00 00:00:00' ),
			array_column( array_slice( $metadata[0]['columns'], 1 ), 'default' )
		);
	}

	/**
	 * Tests FULLTEXT and SPATIAL indexes are metadata-only in PostgreSQL DDL.
	 */
	public function test_translate_fulltext_and_spatial_indexes_as_metadata_only(): void {
		$sql = 'CREATE TABLE wp_search_geo (
			id bigint(20) unsigned NOT NULL,
			body longtext NOT NULL,
			shape point NOT NULL,
			PRIMARY KEY (id),
			FULLTEXT KEY body_fulltext (body),
			SPATIAL KEY shape_spatial (shape),
			KEY id_lookup (id)
		) DEFAULT CHARACTER SET utf8mb4';

		$translator = new WP_PostgreSQL_Create_Table_Translator();

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_search_geo\" (\n  \"id\" __wp_mysql_bigint_20_unsigned NOT NULL,\n  \"body\" __wp_mysql_longtext NOT NULL,\n  \"shape\" __wp_mysql_point NOT NULL,\n  PRIMARY KEY (\"id\")\n)",
				'CREATE INDEX "wp_search_geo__id_lookup" ON "wp_search_geo" ("id")',
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );
		$this->assertSame(
			array( 'PRIMARY', 'body_fulltext', 'shape_spatial', 'id_lookup' ),
			array_column( $metadata[0]['indexes'], 'name' )
		);
		$this->assertSame(
			array( 'BTREE', 'FULLTEXT', 'SPATIAL', 'BTREE' ),
			array_column( $metadata[0]['indexes'], 'index_type' )
		);
		$this->assertNull( $metadata[0]['indexes'][1]['columns'][0]['sub_part'] );
		$this->assertSame( 32, $metadata[0]['indexes'][2]['columns'][0]['sub_part'] );
	}

	/**
	 * Tests temporary IF NOT EXISTS statements.
	 */
	public function test_translate_temporary_if_not_exists(): void {
		$this->assertSame(
			array(
				"CREATE TEMPORARY TABLE IF NOT EXISTS \"wp_tmp\" (\n  \"id\" __wp_mysql_int_11 NOT NULL,\n  PRIMARY KEY (\"id\")\n)",
				'CREATE INDEX IF NOT EXISTS "wp_tmp__id_idx" ON "wp_tmp" ("id")',
			),
			$this->translate(
				'CREATE TEMPORARY TABLE IF NOT EXISTS wp_tmp (
					id int(11) NOT NULL,
					PRIMARY KEY (id),
					KEY id_idx (id)
				) DEFAULT CHARACTER SET utf8mb4'
			)
		);
	}

	/**
	 * Tests MySQL charset metadata is extracted from CREATE TABLE statements.
	 */
	public function test_extract_schema_metadata_preserves_mysql_charsets(): void {
		$translator = new WP_PostgreSQL_Create_Table_Translator();

		$this->assertSame(
			array(
				array(
					'table_name' => 'wp_charset_test',
					'charset'    => 'utf8',
					'collation'  => 'utf8_general_ci',
					'comment'    => '',
					'columns'    => array(
						array(
							'name'      => 'a',
							'type'      => 'varchar(50)',
							'charset'   => 'latin1',
							'collation' => 'latin1_swedish_ci',
							'comment'   => '',
							'ordinal'   => 1,
						),
						array(
							'name'      => 'b',
							'type'      => 'text',
							'charset'   => 'koi8r',
							'collation' => 'koi8r_general_ci',
							'comment'   => '',
							'ordinal'   => 2,
						),
						array(
							'name'      => 'c',
							'type'      => 'binary(1)',
							'charset'   => null,
							'collation' => null,
							'comment'   => '',
							'ordinal'   => 3,
						),
						array(
							'name'      => 'd',
							'type'      => 'int',
							'charset'   => null,
							'collation' => null,
							'comment'   => '',
							'ordinal'   => 4,
						),
					),
				),
			),
			$translator->extract_schema_metadata(
				'CREATE TABLE wp_charset_test (
					a VARCHAR(50) CHARACTER SET latin1,
					b TEXT COLLATE koi8r_general_ci,
					c BINARY,
					d INT
				) DEFAULT CHARSET utf8mb3'
			)
		);
	}

	/**
	 * Tests MySQL table, column, and index comments are extracted from CREATE TABLE statements.
	 */
	public function test_extract_schema_metadata_preserves_mysql_comments(): void {
		$translator = new WP_PostgreSQL_Create_Table_Translator();
		$metadata   = $translator->extract_schema_metadata(
			"CREATE TABLE wp_comment_meta (
				id int NOT NULL COMMENT 'ID comment',
				value varchar(50) COMMENT \"Value comment\",
				KEY value_lookup (value) COMMENT 'Index comment'
			) COMMENT='Table comment'",
			true
		);

		$this->assertSame( 'Table comment', $metadata[0]['comment'] );
		$this->assertSame( array( 'ID comment', 'Value comment' ), array_column( $metadata[0]['columns'], 'comment' ) );
		$this->assertSame( 'Index comment', $metadata[0]['indexes'][0]['comment'] );
	}

	/**
	 * Tests numeric precision and scale are preserved in DDL and metadata.
	 */
	public function test_numeric_precision_and_scale_are_preserved(): void {
		$translator = new WP_PostgreSQL_Create_Table_Translator();
		$sql        = 'CREATE TABLE wp_numeric_test (
			amount DECIMAL(10,2) NOT NULL,
			ratio NUMERIC(12,6),
			score FLOAT(10,3),
			measure DOUBLE(8,4)
		)';

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_numeric_test\" (\n  \"amount\" numeric(10,2) NOT NULL,\n  \"ratio\" __wp_mysql_numeric_12_6,\n  \"score\" __wp_mysql_float_10_3,\n  \"measure\" __wp_mysql_double_8_4\n)",
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql );

		$this->assertSame( 'decimal(10,2)', $metadata[0]['columns'][0]['type'] );
		$this->assertSame( 'numeric(12,6)', $metadata[0]['columns'][1]['type'] );
		$this->assertSame( 'float(10,3)', $metadata[0]['columns'][2]['type'] );
		$this->assertSame( 'double(8,4)', $metadata[0]['columns'][3]['type'] );
	}

	/**
	 * Tests MySQL data type aliases translate while preserving MySQL metadata.
	 */
	public function test_mysql_data_type_aliases_are_supported(): void {
		$translator = new WP_PostgreSQL_Create_Table_Translator();
		$sql        = 'CREATE TABLE wp_alias_test (
			flags BIT(10),
			enabled BOOL NOT NULL DEFAULT 0,
			toggled BOOLEAN,
			amount DEC(10,2),
			fixed_value FIXED(8,3),
			real_value REAL
		)';

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_alias_test\" (\n  \"flags\" __wp_mysql_bit_10,\n  \"enabled\" __wp_mysql_bool NOT NULL DEFAULT '0',\n  \"toggled\" __wp_mysql_boolean,\n  \"amount\" __wp_mysql_dec_10_2,\n  \"fixed_value\" __wp_mysql_fixed_8_3,\n  \"real_value\" __wp_mysql_real\n)",
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql );

		$this->assertSame( 'bit(10)', $metadata[0]['columns'][0]['type'] );
		$this->assertSame( 'bool', $metadata[0]['columns'][1]['type'] );
		$this->assertSame( 'boolean', $metadata[0]['columns'][2]['type'] );
		$this->assertSame( 'dec(10,2)', $metadata[0]['columns'][3]['type'] );
		$this->assertSame( 'fixed(8,3)', $metadata[0]['columns'][4]['type'] );
		$this->assertSame( 'real', $metadata[0]['columns'][5]['type'] );
	}

	/**
	 * Tests MySQL character type aliases translate while preserving MySQL metadata.
	 */
	public function test_mysql_character_type_aliases_are_supported(): void {
		$translator = new WP_PostgreSQL_Create_Table_Translator();
		$sql        = 'CREATE TABLE wp_character_alias_test (
			c1 CHAR,
			c2 CHARACTER(10),
			c3 CHAR VARYING(255),
			c4 CHARACTER VARYING(255),
			c5 NATIONAL CHAR,
			c6 NCHAR,
			c7 NATIONAL CHAR(10),
			c8 NCHAR(10),
			c9 NCHAR VARCHAR(255),
			c10 NCHAR VARYING(255),
			c11 NVARCHAR(255),
			c12 NATIONAL VARCHAR(255),
			c13 NATIONAL CHAR VARYING(255),
			c14 NATIONAL CHARACTER VARYING(255)
		) DEFAULT CHARACTER SET utf8mb4';

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_character_alias_test\" (\n  \"c1\" char(1),\n  \"c2\" char(10),\n  \"c3\" varchar(255),\n  \"c4\" varchar(255),\n  \"c5\" char(1),\n  \"c6\" char(1),\n  \"c7\" char(10),\n  \"c8\" char(10),\n  \"c9\" varchar(255),\n  \"c10\" varchar(255),\n  \"c11\" varchar(255),\n  \"c12\" varchar(255),\n  \"c13\" varchar(255),\n  \"c14\" varchar(255)\n)",
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );

		$this->assertSame(
			array(
				'char(1)',
				'char(10)',
				'varchar(255)',
				'varchar(255)',
				'char(1)',
				'char(1)',
				'char(10)',
				'char(10)',
				'varchar(255)',
				'varchar(255)',
				'varchar(255)',
				'varchar(255)',
				'varchar(255)',
				'varchar(255)',
			),
			array_column( $metadata[0]['columns'], 'type' )
		);
		$this->assertSame(
			array( 'utf8mb4', 'utf8mb4', 'utf8mb4', 'utf8mb4', 'utf8', 'utf8', 'utf8', 'utf8', 'utf8', 'utf8', 'utf8', 'utf8', 'utf8', 'utf8' ),
			array_column( $metadata[0]['columns'], 'charset' )
		);
		$this->assertSame(
			array( 'utf8mb4_unicode_ci', 'utf8mb4_unicode_ci', 'utf8mb4_unicode_ci', 'utf8mb4_unicode_ci', 'utf8_general_ci', 'utf8_general_ci', 'utf8_general_ci', 'utf8_general_ci', 'utf8_general_ci', 'utf8_general_ci', 'utf8_general_ci', 'utf8_general_ci', 'utf8_general_ci', 'utf8_general_ci' ),
			array_column( $metadata[0]['columns'], 'collation' )
		);
	}

	/**
	 * Tests MySQL LONG-prefixed aliases translate while preserving MySQL metadata.
	 */
	public function test_mysql_long_type_aliases_are_supported(): void {
		$translator = new WP_PostgreSQL_Create_Table_Translator();
		$sql        = 'CREATE TABLE wp_long_alias_test (
			c1 LONG VARCHAR,
			c2 LONG CHAR,
			c3 LONG CHAR VARYING,
			c4 LONG CHARACTER,
			c5 LONG CHARACTER VARYING,
			c6 LONG VARBINARY,
			c7 LONG,
			c8 LONG BYTE
		) DEFAULT CHARACTER SET utf8mb4';

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_long_alias_test\" (\n  \"c1\" __wp_mysql_mediumtext,\n  \"c2\" __wp_mysql_mediumtext,\n  \"c3\" __wp_mysql_mediumtext,\n  \"c4\" __wp_mysql_mediumtext,\n  \"c5\" __wp_mysql_mediumtext,\n  \"c6\" __wp_mysql_mediumblob,\n  \"c7\" __wp_mysql_mediumtext,\n  \"c8\" __wp_mysql_mediumblob\n)",
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );

		$this->assertSame(
			array( 'mediumtext', 'mediumtext', 'mediumtext', 'mediumtext', 'mediumtext', 'mediumblob', 'mediumtext', 'mediumblob' ),
			array_column( $metadata[0]['columns'], 'type' )
		);
		$this->assertSame(
			array( 'utf8mb4', 'utf8mb4', 'utf8mb4', 'utf8mb4', 'utf8mb4', null, 'utf8mb4', null ),
			array_column( $metadata[0]['columns'], 'charset' )
		);
		$this->assertSame(
			array( 'utf8mb4_unicode_ci', 'utf8mb4_unicode_ci', 'utf8mb4_unicode_ci', 'utf8mb4_unicode_ci', 'utf8mb4_unicode_ci', null, 'utf8mb4_unicode_ci', null ),
			array_column( $metadata[0]['columns'], 'collation' )
		);
	}

	/**
	 * Tests MySQL SERIAL translates to identity DDL and preserves MySQL metadata.
	 */
	public function test_serial_type_is_supported(): void {
		$translator = new WP_PostgreSQL_Create_Table_Translator();
		$sql        = 'CREATE TABLE wp_serial_test (
			id SERIAL,
			label VARCHAR(20)
		)';

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_serial_test\" (\n  \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT \"id\" UNIQUE,\n  \"label\" varchar(20)\n)",
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );

		$this->assertSame( 'bigint unsigned', $metadata[0]['columns'][0]['type'] );
		$this->assertSame( 'NO', $metadata[0]['columns'][0]['nullable'] );
		$this->assertSame( 'auto_increment', $metadata[0]['columns'][0]['extra'] );
		$this->assertSame( 'id', $metadata[0]['indexes'][0]['name'] );
		$this->assertSame( '0', $metadata[0]['indexes'][0]['non_unique'] );
		$this->assertSame( 'id', $metadata[0]['indexes'][0]['columns'][0]['column_name'] );
	}

	/**
	 * Tests MySQL enumerated string types translate while preserving metadata.
	 */
	public function test_enum_and_set_types_are_supported(): void {
		$translator = new WP_PostgreSQL_Create_Table_Translator();
		$sql        = "CREATE TABLE wp_enum_set_test (
			status ENUM('draft','published') NOT NULL DEFAULT 'draft',
			flags SET('featured','archived') DEFAULT 'featured'
		) DEFAULT CHARACTER SET utf8mb4";

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_enum_set_test\" (\n  \"status\" __wp_mysql_enum_02ccf983d79439de NOT NULL DEFAULT 'draft',\n  \"flags\" __wp_mysql_set_3c255ba5f59d3194 DEFAULT 'featured'\n)",
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );

		$this->assertSame( "enum('draft','published')", $metadata[0]['columns'][0]['type'] );
		$this->assertSame( "set('featured','archived')", $metadata[0]['columns'][1]['type'] );
		$this->assertSame( array( 'utf8mb4', 'utf8mb4' ), array_column( $metadata[0]['columns'], 'charset' ) );
		$this->assertSame( array( 'draft', 'featured' ), array_column( $metadata[0]['columns'], 'default' ) );
	}

	/**
	 * Tests MySQL JSON translates to text storage while preserving MySQL metadata.
	 */
	public function test_json_type_is_supported(): void {
		$translator = new WP_PostgreSQL_Create_Table_Translator();
		$sql        = 'CREATE TABLE wp_json_test (
			id int NOT NULL,
			payload JSON DEFAULT NULL
		) DEFAULT CHARACTER SET utf8mb4';

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_json_test\" (\n  \"id\" integer NOT NULL,\n  \"payload\" __wp_mysql_json DEFAULT NULL\n)",
			),
			$translator->translate_schema( $sql )
		);

		$metadata = $translator->extract_schema_metadata( $sql, true );

		$this->assertSame( 'json', $metadata[0]['columns'][1]['type'] );
		$this->assertNull( $metadata[0]['columns'][1]['charset'] );
		$this->assertNull( $metadata[0]['columns'][1]['collation'] );
		$this->assertSame( 'YES', $metadata[0]['columns'][1]['nullable'] );
		$this->assertNull( $metadata[0]['columns'][1]['default'] );
	}

	/**
	 * Tests unsupported CREATE TABLE ... SELECT statements are rejected.
	 */
	public function test_translate_rejects_create_table_as_select(): void {
		$this->expectException( InvalidArgumentException::class );
		$this->translate( 'CREATE TABLE wp_copy AS SELECT 1 AS id' );
	}

	/**
	 * Tests inline and table CHECK constraints are translated.
	 */
	public function test_translate_supports_check_constraints(): void {
		$sql = 'CREATE TABLE wp_inline_check (
			id int CHECK (id > 0),
			`score` int NOT NULL CHECK (`score` < 10),
			CONSTRAINT c CHECK (id < 100),
			CHECK (score >= 0)
		)';

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_inline_check\" (\n  \"id\" integer CONSTRAINT \"wp_inline_check_chk_1\" CHECK (id > 0),\n  \"score\" integer NOT NULL CONSTRAINT \"wp_inline_check_chk_2\" CHECK (\"score\" < 10),\n  CONSTRAINT \"c\" CHECK (id < 100),\n  CONSTRAINT \"wp_inline_check_chk_3\" CHECK (score >= 0)\n)",
			),
			$this->translate( $sql )
		);

		$translator = new WP_PostgreSQL_Create_Table_Translator();
		$metadata   = $translator->extract_schema_metadata( $sql, true );

		$this->assertSame( array( 'id', 'score' ), array_column( $metadata[0]['columns'], 'name' ) );
		$this->assertSame( array(), $metadata[0]['indexes'] );
		$this->assertSame( array(), $metadata[0]['foreign_keys'] );
		$this->assertSame(
			array(
				array(
					'name'         => 'wp_inline_check_chk_1',
					'check_clause' => 'id > 0',
					'enforced'     => 'YES',
				),
				array(
					'name'         => 'wp_inline_check_chk_2',
					'check_clause' => '"score" < 10',
					'enforced'     => 'YES',
				),
				array(
					'name'         => 'c',
					'check_clause' => 'id < 100',
					'enforced'     => 'YES',
				),
				array(
					'name'         => 'wp_inline_check_chk_3',
					'check_clause' => 'score >= 0',
					'enforced'     => 'YES',
				),
			),
			$metadata[0]['checks']
		);
	}

	/**
	 * Tests CHECK metadata preserves PostgreSQL-only expression rewrites.
	 */
	public function test_translate_check_metadata_tracks_postgresql_expression_when_it_differs(): void {
		$sql        = 'CREATE TABLE wp_json_check (data JSON CHECK (json_valid(data)))';
		$translator = new WP_PostgreSQL_Create_Table_Translator();
		$metadata   = $translator->extract_schema_metadata( $sql, true );

		$this->assertSame(
			array(
				array(
					'name'                    => 'wp_json_check_chk_1',
					'check_clause'            => 'json_valid(data)',
					'enforced'                => 'YES',
					'postgresql_check_clause' => '(CASE WHEN data IS NULL THEN NULL ELSE (CAST(data AS jsonb) IS NOT NULL) END)',
				),
			),
			$metadata[0]['checks']
		);
	}

	/**
	 * Tests NOT ENFORCED CHECK constraints use PostgreSQL placeholders.
	 */
	public function test_translate_not_enforced_check_constraints_as_postgresql_placeholders(): void {
		$sql = 'CREATE TABLE wp_inline_check (
			id int CHECK (id > 0) NOT ENFORCED,
			score int CHECK (score > 0) ENFORCED,
			CONSTRAINT c CHECK (id < 100) NOT ENFORCED
		)';

		$this->assertSame(
			array(
				"CREATE TABLE \"wp_inline_check\" (\n  \"id\" integer CONSTRAINT \"wp_inline_check_chk_1\" CHECK (true),\n  \"score\" integer CONSTRAINT \"wp_inline_check_chk_2\" CHECK (score > 0),\n  CONSTRAINT \"c\" CHECK (true)\n)",
			),
			$this->translate( $sql )
		);

		$translator = new WP_PostgreSQL_Create_Table_Translator();
		$metadata   = $translator->extract_schema_metadata( $sql, true );

		$this->assertSame( array( 'YES', 'YES' ), array_column( $metadata[0]['columns'], 'nullable' ) );
		$this->assertSame(
			array(
				array(
					'name'         => 'wp_inline_check_chk_1',
					'check_clause' => 'id > 0',
					'enforced'     => 'NO',
				),
				array(
					'name'         => 'wp_inline_check_chk_2',
					'check_clause' => 'score > 0',
					'enforced'     => 'YES',
				),
				array(
					'name'         => 'c',
					'check_clause' => 'id < 100',
					'enforced'     => 'NO',
				),
			),
			$metadata[0]['checks']
		);
	}

	/**
	 * Translates MySQL CREATE TABLE SQL.
	 *
	 * @param string $sql MySQL CREATE TABLE statement.
	 * @return string[] PostgreSQL DDL statements.
	 */
	private function translate( string $sql ): array {
		$translator = new WP_PostgreSQL_Create_Table_Translator();
		return $translator->translate_schema( $sql );
	}
}
