<?php

use PHPUnit\Framework\TestCase;

/**
 * Unit tests for PostgreSQL WordPress install hooks.
 */
class WP_PostgreSQL_Install_Functions_Tests extends TestCase {
	/**
	 * Tests schema installation translates WordPress MySQL DDL before querying.
	 */
	public function test_postgresql_make_db_current_silent_translates_schema(): void {
		$result = $this->run_isolated_install_script(
			<<<'PHP'
require_once getcwd() . '/bootstrap.php';

$root = sys_get_temp_dir() . '/wp-pg-install-' . str_replace( '.', '-', uniqid( '', true ) ) . '/';
register_shutdown_function( 'wp_pg_install_test_remove_tree', $root );
mkdir( $root . 'wp-admin/includes', 0777, true );
file_put_contents(
	$root . 'wp-admin/includes/schema.php',
	'<?php
function wp_get_db_schema() {
	return "CREATE TABLE wp_options (
		option_id bigint(20) unsigned NOT NULL auto_increment,
		option_name varchar(191) NOT NULL default \'\',
		option_value longtext NOT NULL,
		autoload varchar(20) NOT NULL default \'yes\',
		PRIMARY KEY (option_id),
		UNIQUE KEY option_name (option_name),
		KEY autoload (autoload)
	) DEFAULT CHARACTER SET utf8mb4";
}
'
);

define( 'ABSPATH', $root );

$GLOBALS['wpdb'] = new class() {
	public $last_error = '';
	public $queries    = array();

	public function query( $statement ) {
		$this->queries[] = $statement;
		return true;
	}
};

require_once getcwd() . '/../../plugin-sqlite-database-integration/wp-includes/postgresql/install-functions.php';

$result = postgresql_make_db_current_silent();

wp_pg_install_test_remove_tree( $root );
wp_pg_install_test_respond(
	array(
		'result'  => $result,
		'queries' => $GLOBALS['wpdb']->queries,
	)
);
PHP
		);

		$this->assertTrue( $result['result'] );
		$this->assertSame(
			array(
				"CREATE TABLE \"wp_options\" (\n  \"option_id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  \"option_name\" varchar(191) NOT NULL DEFAULT '',\n  \"option_value\" __wp_mysql_longtext NOT NULL,\n  \"autoload\" varchar(20) NOT NULL DEFAULT 'yes',\n  PRIMARY KEY (\"option_id\")\n)",
				'CREATE UNIQUE INDEX "wp_options__option_name" ON "wp_options" ("option_name")',
				'CREATE INDEX "wp_options__autoload" ON "wp_options" ("autoload")',
			),
			$result['queries']
		);
	}

	/**
	 * Tests schema installation routes original MySQL DDL through the PostgreSQL driver.
	 */
	public function test_postgresql_make_db_current_silent_routes_schema_through_driver(): void {
		$result = $this->run_isolated_install_script(
			<<<'PHP'
	require_once getcwd() . '/bootstrap.php';

	class WP_PostgreSQL_Install_Test_PDO extends PDO {
		#[\ReturnTypeWillChange]
		public function getAttribute( $attribute ) {
			if ( PDO::ATTR_DRIVER_NAME === $attribute ) {
				return 'pgsql';
			}

			return parent::getAttribute( $attribute );
		}
	}

	class WP_PostgreSQL_Install_Test_Connection extends WP_PostgreSQL_Connection {
		public $queries        = array();
		public $domain_queries = array();
		private $test_pdo;

		public function __construct() {
			$this->test_pdo = new WP_PostgreSQL_Install_Test_PDO( 'sqlite::memory:' );
		}

		public function get_pdo(): PDO {
			return $this->test_pdo;
		}

		public function get_driver_name(): string {
			return 'pgsql';
		}

		public function quote( $value, int $type = PDO::PARAM_STR ): string {
			return $this->test_pdo->quote( $value, $type );
		}

		public function query( string $sql, array $params = array() ): PDOStatement {
			if ( 0 === strpos( $sql, 'DO $wp_mysql_' ) ) {
				$this->domain_queries[] = $sql;
				return $this->test_pdo->query( 'SELECT 1' );
			}

			$this->queries[] = array(
				'sql'    => $sql,
				'params' => $params,
			);

			return $this->test_pdo->query( 'SELECT 1' );
		}
	}

	class WP_PostgreSQL_Install_Test_Driver extends WP_PostgreSQL_Driver {
		public $queries       = array();
		public $stored_schema = '';

		public function query( string $query, $fetch_mode = PDO::FETCH_OBJ, ...$fetch_mode_args ) {
			$this->queries[] = $query;
			return 0;
		}

		public function sync_postgresql_catalog_schema_metadata( string $query ): void {
			$this->stored_schema = $query;
		}
	}

	$root = sys_get_temp_dir() . '/wp-pg-install-' . str_replace( '.', '-', uniqid( '', true ) ) . '/';
	register_shutdown_function( 'wp_pg_install_test_remove_tree', $root );
	mkdir( $root . 'wp-admin/includes', 0777, true );
	file_put_contents(
		$root . 'wp-admin/includes/schema.php',
		'<?php
	function wp_get_db_schema() {
		return "CREATE TABLE wp_options (
			option_id bigint(20) unsigned NOT NULL auto_increment,
			option_name varchar(191) NOT NULL default \'\',
			option_value longtext NOT NULL,
			autoload varchar(20) NOT NULL default \'yes\',
			PRIMARY KEY (option_id),
			UNIQUE KEY option_name (option_name)
		) DEFAULT CHARACTER SET utf8mb4";
	}
	'
	);

	define( 'ABSPATH', $root );

	$connection       = new WP_PostgreSQL_Install_Test_Connection();
	$driver           = new WP_PostgreSQL_Install_Test_Driver( $connection, 'WordPress' );
	$GLOBALS['wpdb'] = new class( $driver ) {
		public $dbh;
		public $last_error = '';
		public $fallback_query_called = false;

		public function __construct( $driver ) {
			$this->dbh = $driver;
		}

		public function query( $statement ) {
			$this->fallback_query_called = true;
			throw new RuntimeException( '$wpdb->query() should not receive translated PostgreSQL DDL.' );
		}
	};

	require_once getcwd() . '/../../plugin-sqlite-database-integration/wp-includes/postgresql/install-functions.php';

	$result = postgresql_make_db_current_silent();

	wp_pg_install_test_remove_tree( $root );
	wp_pg_install_test_respond(
			array(
				'result'                => $result,
				'queries'               => $driver->queries,
				'connection_queries'    => array_column( $connection->queries, 'sql' ),
				'domain_queries'        => $connection->domain_queries,
				'fallback_query_called' => $GLOBALS['wpdb']->fallback_query_called,
				'stored_schema'         => $driver->stored_schema,
			)
		);
	PHP
		);

		$this->assertTrue( $result['result'] );
		$this->assertFalse( $result['fallback_query_called'] );
		$this->assertSame( array(), $result['domain_queries'] );
		$this->assertSame( '', $result['stored_schema'] );
		$this->assertCount( 1, $result['queries'] );
		$this->assertStringStartsWith( 'CREATE TABLE wp_options', $result['queries'][0] );
		$this->assertStringContainsString( 'UNIQUE KEY option_name (option_name)', $result['queries'][0] );
		$this->assertStringContainsString(
			'CREATE SCHEMA IF NOT EXISTS "__wp_mysql_information_schema"',
			implode( "\n", $result['connection_queries'] )
		);
		$this->assertStringContainsString(
			'COMMENT ON SCHEMA "__wp_mysql_information_schema"',
			implode( "\n", $result['connection_queries'] )
		);
		$this->assertStringContainsString(
			'CREATE OR REPLACE VIEW "__wp_mysql_information_schema"."tables" AS',
			implode( "\n", $result['connection_queries'] )
		);
		$this->assertStringContainsString(
			'CREATE OR REPLACE VIEW "__wp_mysql_information_schema"."keywords" AS',
			implode( "\n", $result['connection_queries'] )
		);
	}

	/**
	 * Tests driver-backed schema installation uses PostgreSQL catalog metadata, not hidden side tables.
	 */
	public function test_postgresql_make_db_current_silent_uses_catalog_metadata_with_driver(): void {
		$result = $this->run_isolated_install_script(
			<<<'PHP'
require_once getcwd() . '/bootstrap.php';

class WP_PostgreSQL_Install_Catalog_Test_PDO extends PDO {
	#[\ReturnTypeWillChange]
	public function getAttribute( $attribute ) {
		if ( PDO::ATTR_DRIVER_NAME === $attribute ) {
			return 'pgsql';
		}

		if ( PDO::ATTR_SERVER_VERSION === $attribute ) {
			return '16.0';
		}

		return parent::getAttribute( $attribute );
	}
}

class WP_PostgreSQL_Install_Catalog_Test_Connection extends WP_PostgreSQL_Connection {
	public $queries = array();
	private $test_pdo;

	public function __construct() {
		$this->test_pdo = new WP_PostgreSQL_Install_Catalog_Test_PDO( 'sqlite::memory:' );
	}

	public function get_pdo(): PDO {
		return $this->test_pdo;
	}

	public function get_driver_name(): string {
		return 'pgsql';
	}

	public function quote( $value, int $type = PDO::PARAM_STR ): string {
		return $this->test_pdo->quote( $value, $type );
	}

	public function query( string $sql, array $params = array() ): PDOStatement {
		foreach (
			array(
				WP_PostgreSQL_Driver::MYSQL_TABLE_METADATA_TABLE,
				WP_PostgreSQL_Driver::MYSQL_COLUMN_METADATA_TABLE,
				WP_PostgreSQL_Driver::MYSQL_INDEX_METADATA_TABLE,
				WP_PostgreSQL_Driver::MYSQL_FOREIGN_KEY_METADATA_TABLE,
				WP_PostgreSQL_Driver::MYSQL_CHECK_METADATA_TABLE,
			) as $metadata_table
		) {
			if ( 1 === preg_match( '/\b(?:CREATE|ALTER|DROP|INSERT\s+INTO|UPDATE|DELETE\s+FROM|FROM|JOIN)\s+(?:(?:"?[A-Za-z0-9_]+"?)\.)?"?' . preg_quote( $metadata_table, '/' ) . '"?\b/i', $sql ) ) {
				throw new RuntimeException( 'Hidden metadata table SQL was not expected during PostgreSQL install.' );
			}
		}

		$this->queries[] = array(
			'sql'    => $sql,
			'params' => $params,
		);

		return $this->test_pdo->query( 'SELECT 1' );
	}
}

$root = sys_get_temp_dir() . '/wp-pg-install-' . str_replace( '.', '-', uniqid( '', true ) ) . '/';
register_shutdown_function( 'wp_pg_install_test_remove_tree', $root );
mkdir( $root . 'wp-admin/includes', 0777, true );
file_put_contents(
	$root . 'wp-admin/includes/schema.php',
	'<?php
function wp_get_db_schema() {
	return "CREATE TABLE wp_options (
		option_id bigint(20) unsigned NOT NULL auto_increment,
		option_name varchar(191) NOT NULL default \'\',
		option_value longtext NOT NULL,
		autoload varchar(20) NOT NULL default \'yes\',
		PRIMARY KEY (option_id),
		UNIQUE KEY option_name (option_name)
	) DEFAULT CHARACTER SET utf8mb4";
}
'
);

define( 'ABSPATH', $root );

$connection       = new WP_PostgreSQL_Install_Catalog_Test_Connection();
$GLOBALS['wpdb'] = new class( $connection ) {
	public $dbh;
	public $last_error = '';

	public function __construct( $connection ) {
		$this->dbh = new WP_PostgreSQL_Driver( $connection, 'WordPress' );
	}

	public function query( $statement ) {
		throw new RuntimeException( '$wpdb->query() should not receive translated PostgreSQL DDL.' );
	}
};

require_once getcwd() . '/../../plugin-sqlite-database-integration/wp-includes/postgresql/install-functions.php';

$result = postgresql_make_db_current_silent();

wp_pg_install_test_remove_tree( $root );
wp_pg_install_test_respond(
	array(
		'result'  => $result,
		'queries' => array_column( $connection->queries, 'sql' ),
		'params'  => array_column( $connection->queries, 'params' ),
	)
);
PHP
		);

		$sql = implode( "\n", $result['queries'] );

		$this->assertTrue( $result['result'] );
		$this->assertStringContainsString( 'DO $wp_mysql_text_domain$', $sql );
		$this->assertStringContainsString( 'CREATE TABLE "wp_options"', $sql );
		$this->assertStringContainsString( 'DO $wp_mysql_identity_sequence_comment$', $sql );
		$this->assertStringContainsString( 'CREATE SCHEMA IF NOT EXISTS "__wp_mysql_information_schema"', $sql );
		$this->assertStringContainsString( 'COMMENT ON SCHEMA "__wp_mysql_information_schema"', $sql );
		$this->assertStringContainsString( 'CREATE OR REPLACE VIEW "__wp_mysql_information_schema"."tables" AS', $sql );
		$this->assertStringContainsString( 'CREATE OR REPLACE VIEW "__wp_mysql_information_schema"."keywords" AS', $sql );

		foreach (
			array(
				WP_PostgreSQL_Driver::MYSQL_TABLE_METADATA_TABLE,
				WP_PostgreSQL_Driver::MYSQL_COLUMN_METADATA_TABLE,
				WP_PostgreSQL_Driver::MYSQL_INDEX_METADATA_TABLE,
				WP_PostgreSQL_Driver::MYSQL_FOREIGN_KEY_METADATA_TABLE,
				WP_PostgreSQL_Driver::MYSQL_CHECK_METADATA_TABLE,
			) as $metadata_table
		) {
			$this->assertSame(
				0,
				preg_match( '/\b(?:CREATE|ALTER|DROP|INSERT\s+INTO|UPDATE|DELETE\s+FROM|FROM|JOIN)\s+(?:(?:"?[A-Za-z0-9_]+"?)\.)?"?' . preg_quote( $metadata_table, '/' ) . '"?\b/i', $sql ),
				$metadata_table
			);
		}
	}

	/**
	 * Tests schema installation refreshes existing PostgreSQL information_schema compatibility views.
	 */
	public function test_postgresql_make_db_current_silent_refreshes_existing_information_schema_views(): void {
		$result = $this->run_isolated_install_script(
			<<<'PHP'
require_once getcwd() . '/bootstrap.php';

class WP_PostgreSQL_Install_View_Reuse_Test_PDO extends PDO {
	#[\ReturnTypeWillChange]
	public function getAttribute( $attribute ) {
		if ( PDO::ATTR_DRIVER_NAME === $attribute ) {
			return 'pgsql';
		}

		if ( PDO::ATTR_SERVER_VERSION === $attribute ) {
			return '16.0';
		}

		return parent::getAttribute( $attribute );
	}
}

class WP_PostgreSQL_Install_View_Reuse_Test_Connection extends WP_PostgreSQL_Connection {
	public $installed_relations = array();
	public $queries             = array();
	private $test_pdo;

	public function __construct() {
		$this->test_pdo = new WP_PostgreSQL_Install_View_Reuse_Test_PDO( 'sqlite::memory:' );
	}

	public function get_pdo(): PDO {
		return $this->test_pdo;
	}

	public function get_driver_name(): string {
		return 'pgsql';
	}

	public function quote( $value, int $type = PDO::PARAM_STR ): string {
		return $this->test_pdo->quote( $value, $type );
	}

	public function query( string $sql, array $params = array() ): PDOStatement {
		foreach (
			array(
				WP_PostgreSQL_Driver::MYSQL_TABLE_METADATA_TABLE,
				WP_PostgreSQL_Driver::MYSQL_COLUMN_METADATA_TABLE,
				WP_PostgreSQL_Driver::MYSQL_INDEX_METADATA_TABLE,
				WP_PostgreSQL_Driver::MYSQL_FOREIGN_KEY_METADATA_TABLE,
				WP_PostgreSQL_Driver::MYSQL_CHECK_METADATA_TABLE,
			) as $metadata_table
		) {
			if ( 1 === preg_match( '/\b(?:CREATE|ALTER|DROP|INSERT\s+INTO|UPDATE|DELETE\s+FROM|FROM|JOIN)\s+(?:(?:"?[A-Za-z0-9_]+"?)\.)?"?' . preg_quote( $metadata_table, '/' ) . '"?\b/i', $sql ) ) {
				throw new RuntimeException( 'Hidden metadata table SQL was not expected during PostgreSQL install.' );
			}
		}

		$this->queries[] = array(
			'sql'    => $sql,
			'params' => $params,
		);

		if ( false !== strpos( $sql, 'FROM pg_catalog.pg_class c' ) && false !== strpos( $sql, 'c.relkind IN' ) ) {
			$selects = array();
			foreach ( $this->installed_relations as $index => $relation ) {
				$selects[] = 0 === $index
					? sprintf( 'SELECT %s AS relname', $this->test_pdo->quote( $relation ) )
					: sprintf( 'SELECT %s', $this->test_pdo->quote( $relation ) );
			}

			return $this->test_pdo->query( implode( "\nUNION ALL ", $selects ) );
		}

		if ( false !== strpos( $sql, 'FROM pg_catalog.pg_class c' ) && false !== strpos( $sql, 'c.relname IN' ) ) {
			return $this->test_pdo->query( 'SELECT NULL AS relname WHERE 0 = 1' );
		}

		return $this->test_pdo->query( 'SELECT 1' );
	}
}

$root = sys_get_temp_dir() . '/wp-pg-install-' . str_replace( '.', '-', uniqid( '', true ) ) . '/';
register_shutdown_function( 'wp_pg_install_test_remove_tree', $root );
mkdir( $root . 'wp-admin/includes', 0777, true );
file_put_contents(
	$root . 'wp-admin/includes/schema.php',
	'<?php
function wp_get_db_schema() {
	return "CREATE TABLE wp_options (
		option_id bigint(20) unsigned NOT NULL auto_increment,
		option_name varchar(191) NOT NULL default \'\',
		option_value longtext NOT NULL,
		autoload varchar(20) NOT NULL default \'yes\',
		PRIMARY KEY (option_id),
		UNIQUE KEY option_name (option_name)
	) DEFAULT CHARACTER SET utf8mb4";
}
'
);

define( 'ABSPATH', $root );

$connection = new WP_PostgreSQL_Install_View_Reuse_Test_Connection();
$driver     = new WP_PostgreSQL_Driver( $connection, 'WordPress' );

$get_definitions = Closure::bind(
	function (): array {
		return $this->get_postgresql_information_schema_compatibility_view_definitions();
	},
	$driver,
	WP_PostgreSQL_Driver::class
);

$connection->installed_relations = array_keys( $get_definitions() );

$GLOBALS['wpdb'] = new class( $driver ) {
	public $dbh;
	public $last_error = '';

	public function __construct( $driver ) {
		$this->dbh = $driver;
	}

	public function query( $statement ) {
		throw new RuntimeException( '$wpdb->query() should not receive translated PostgreSQL DDL.' );
	}
};

require_once getcwd() . '/../../plugin-sqlite-database-integration/wp-includes/postgresql/install-functions.php';

$result = postgresql_make_db_current_silent();

wp_pg_install_test_remove_tree( $root );
wp_pg_install_test_respond(
	array(
		'result'  => $result,
		'queries' => array_column( $connection->queries, 'sql' ),
		'params'  => array_column( $connection->queries, 'params' ),
	)
);
PHP
		);

		$sql = implode( "\n", $result['queries'] );

		$this->assertTrue( $result['result'] );
		$this->assertStringContainsString( 'CREATE TABLE "wp_options"', $sql );
		$this->assertStringNotContainsString( 'SELECT c.relname', $sql );
		$this->assertStringContainsString( 'CREATE SCHEMA IF NOT EXISTS "__wp_mysql_information_schema"', $sql );
		$this->assertStringContainsString( 'COMMENT ON SCHEMA "__wp_mysql_information_schema"', $sql );
		$this->assertStringContainsString( 'CREATE OR REPLACE VIEW "__wp_mysql_information_schema"."tables" AS', $sql );
		$this->assertStringContainsString( 'current_database()', $sql );

		foreach (
			array(
				WP_PostgreSQL_Driver::MYSQL_TABLE_METADATA_TABLE,
				WP_PostgreSQL_Driver::MYSQL_COLUMN_METADATA_TABLE,
				WP_PostgreSQL_Driver::MYSQL_INDEX_METADATA_TABLE,
				WP_PostgreSQL_Driver::MYSQL_FOREIGN_KEY_METADATA_TABLE,
				WP_PostgreSQL_Driver::MYSQL_CHECK_METADATA_TABLE,
			) as $metadata_table
		) {
			$this->assertSame(
				0,
				preg_match( '/\b(?:CREATE|ALTER|DROP|INSERT\s+INTO|UPDATE|DELETE\s+FROM|FROM|JOIN)\s+(?:(?:"?[A-Za-z0-9_]+"?)\.)?"?' . preg_quote( $metadata_table, '/' ) . '"?\b/i', $sql ),
				$metadata_table
			);
		}
	}

	/**
	 * Tests wp_install() creates schema before running populate helpers.
	 */
	public function test_wp_install_creates_schema_before_populating_site(): void {
		$result = $this->run_isolated_install_script(
			<<<'PHP'
function do_action( $hook, ...$args ) {
	wp_pg_install_test_event( array( 'do_action', $hook ) );
}

require_once getcwd() . '/bootstrap.php';

function wp_pg_install_test_event( $event ) {
	$GLOBALS['wp_pg_install_test_events'][] = $event;
}

function wp_check_mysql_version() {
	wp_pg_install_test_event( 'wp_check_mysql_version' );
}

function wp_cache_flush() {
	wp_pg_install_test_event( 'wp_cache_flush' );
}

function wp_unschedule_hook( $hook ) {
	wp_pg_install_test_event( array( 'wp_unschedule_hook', $hook ) );
}

function wp_schedule_event( $timestamp, $recurrence, $hook ) {
	wp_pg_install_test_event( array( 'wp_schedule_event', $recurrence, $hook, is_numeric( $timestamp ) ) );
}

function populate_options() {
	wp_pg_install_test_event( 'populate_options' );
}

function populate_roles() {
	wp_pg_install_test_event( 'populate_roles' );
}

function update_option( $option, $value, $autoload = null ) {
	wp_pg_install_test_event( array( 'update_option', $option, $value, $autoload ) );
	return true;
}

function wp_guess_url() {
	wp_pg_install_test_event( 'wp_guess_url' );
	return 'https://example.test';
}

function username_exists( $user_name ) {
	wp_pg_install_test_event( array( 'username_exists', $user_name ) );
	return false;
}

function wp_generate_password( $length, $special_chars ) {
	wp_pg_install_test_event( array( 'wp_generate_password', $length, $special_chars ) );
	return 'generated-password';
}

function __( $text, $domain = null ) {
	return $text;
}

function wp_create_user( $user_name, $password, $user_email ) {
	wp_pg_install_test_event( array( 'wp_create_user', $user_name, $password, $user_email ) );
	return 42;
}

function update_user_meta( $user_id, $meta_key, $meta_value ) {
	wp_pg_install_test_event( array( 'update_user_meta', $user_id, $meta_key, $meta_value ) );
	return true;
}

class WP_User {
	public $ID;
	public $user_url;

	public function __construct( $user_id ) {
		$this->ID = $user_id;
		wp_pg_install_test_event( array( 'WP_User::__construct', $user_id ) );
	}

	public function set_role( $role ) {
		wp_pg_install_test_event( array( 'WP_User::set_role', $role ) );
	}
}

function wp_update_user( $user ) {
	wp_pg_install_test_event( array( 'wp_update_user', $user->ID, $user->user_url ) );
	return $user->ID;
}

function wp_install_defaults( $user_id ) {
	wp_pg_install_test_event( array( 'wp_install_defaults', $user_id ) );
}

function wp_install_maybe_enable_pretty_permalinks() {
	wp_pg_install_test_event( 'wp_install_maybe_enable_pretty_permalinks' );
}

function flush_rewrite_rules() {
	wp_pg_install_test_event( 'flush_rewrite_rules' );
}

function wp_new_blog_notification( $blog_title, $guessurl, $user_id, $password ) {
	wp_pg_install_test_event( array( 'wp_new_blog_notification', $blog_title, $guessurl, $user_id, $password ) );
}

$root = sys_get_temp_dir() . '/wp-pg-install-' . str_replace( '.', '-', uniqid( '', true ) ) . '/';
register_shutdown_function( 'wp_pg_install_test_remove_tree', $root );
mkdir( $root . 'wp-admin/includes', 0777, true );
file_put_contents(
	$root . 'wp-admin/includes/schema.php',
	'<?php
function wp_get_db_schema() {
	return "CREATE TABLE wp_options (
		option_id bigint(20) unsigned NOT NULL auto_increment,
		option_name varchar(191) NOT NULL default \'\',
		option_value longtext NOT NULL,
		autoload varchar(20) NOT NULL default \'yes\',
		PRIMARY KEY (option_id),
		UNIQUE KEY option_name (option_name)
	) DEFAULT CHARACTER SET utf8mb4";
}
'
);

define( 'ABSPATH', $root );
define( 'HOUR_IN_SECONDS', 3600 );
$GLOBALS['wp_pg_install_test_events'] = array();
$GLOBALS['wpdb']                      = new class() {
	public $last_error = '';

	public function query( $statement ) {
		wp_pg_install_test_event( array( 'schema_query', $statement ) );
		return true;
	}
};

require_once getcwd() . '/../../plugin-sqlite-database-integration/wp-includes/postgresql/install-functions.php';

$install_result = wp_install( 'Example Site', 'admin', 'admin@example.test', true, '', 'secret-password', 'en_US' );

wp_pg_install_test_remove_tree( $root );
wp_pg_install_test_respond(
	array(
		'events' => $GLOBALS['wp_pg_install_test_events'],
		'result' => $install_result,
	)
);
PHP
		);

		$this->assertSame(
			array(
				array(
					'schema_query',
					"CREATE TABLE \"wp_options\" (\n  \"option_id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  \"option_name\" varchar(191) NOT NULL DEFAULT '',\n  \"option_value\" __wp_mysql_longtext NOT NULL,\n  \"autoload\" varchar(20) NOT NULL DEFAULT 'yes',\n  PRIMARY KEY (\"option_id\")\n)",
				),
				array(
					'schema_query',
					'CREATE UNIQUE INDEX "wp_options__option_name" ON "wp_options" ("option_name")',
				),
				array( 'wp_unschedule_hook', 'wp_version_check' ),
				array( 'wp_unschedule_hook', 'wp_update_plugins' ),
				array( 'wp_unschedule_hook', 'wp_update_themes' ),
				array( 'wp_schedule_event', 'twicedaily', 'wp_version_check', true ),
				array( 'wp_schedule_event', 'twicedaily', 'wp_update_plugins', true ),
				array( 'wp_schedule_event', 'twicedaily', 'wp_update_themes', true ),
				'populate_options',
				'populate_roles',
			),
			array_slice( $result['events'], 2, 10 )
		);
		$this->assertContains(
			array( 'update_option', 'fresh_site', 1, false ),
			$result['events']
		);
		$this->assertSame( 42, $result['result']['user_id'] );
		$this->assertSame( 'secret-password', $result['result']['password'] );
	}

	/**
	 * Tests network installation creates the global schema through the translator.
	 */
	public function test_install_network_creates_postgresql_global_schema(): void {
		$result = $this->run_isolated_install_script(
			<<<'PHP'
require_once getcwd() . '/bootstrap.php';

$root = sys_get_temp_dir() . '/wp-pg-install-' . str_replace( '.', '-', uniqid( '', true ) ) . '/';
register_shutdown_function( 'wp_pg_install_test_remove_tree', $root );
mkdir( $root . 'wp-admin/includes', 0777, true );
file_put_contents(
	$root . 'wp-admin/includes/schema.php',
	'<?php
function wp_get_db_schema( $scope = "all" ) {
	if ( "global" !== $scope ) {
		throw new RuntimeException( "Unexpected schema scope: " . $scope );
	}
	return "CREATE TABLE wp_site (
		id bigint(20) NOT NULL auto_increment,
		domain varchar(200) NOT NULL default \'\',
		path varchar(100) NOT NULL default \'\',
		PRIMARY KEY (id),
		KEY domain (domain(140),path(51))
	) DEFAULT CHARACTER SET utf8mb4";
}
'
);

define( 'ABSPATH', $root );

$GLOBALS['wpdb'] = new class() {
	public $last_error = '';
	public $queries    = array();

	public function query( $statement ) {
		$this->queries[] = $statement;
		return true;
	}
};

require_once getcwd() . '/../../plugin-sqlite-database-integration/wp-includes/postgresql/install-functions.php';

install_network();

$installing_network = defined( 'WP_INSTALLING_NETWORK' ) && WP_INSTALLING_NETWORK;

wp_pg_install_test_remove_tree( $root );
wp_pg_install_test_respond(
	array(
		'installing_network' => $installing_network,
		'queries'            => $GLOBALS['wpdb']->queries,
	)
);
PHP
		);

		$this->assertTrue( $result['installing_network'] );
		$this->assertSame(
			array(
				"CREATE TABLE \"wp_site\" (\n  \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  \"domain\" varchar(200) NOT NULL DEFAULT '',\n  \"path\" varchar(100) NOT NULL DEFAULT '',\n  PRIMARY KEY (\"id\")\n)",
				'CREATE INDEX "wp_site__domain" ON "wp_site" (SUBSTR(CAST("domain" AS text), 1, 140), SUBSTR(CAST("path" AS text), 1, 51))',
			),
			$result['queries']
		);
	}

	/**
	 * Runs an install-functions script in a separate PHP process.
	 *
	 * @param string $script Script body without the opening PHP tag.
	 * @return array Decoded JSON response from the script.
	 */
	private function run_isolated_install_script( string $script ): array {
		$script_file = tempnam( sys_get_temp_dir(), 'wp_pg_install_' );
		if ( false === $script_file ) {
			$this->fail( 'Could not create temporary install-functions test script.' );
		}

		$script_written = file_put_contents(
			$script_file,
			"<?php\n" . $this->get_isolated_script_prelude() . "\n" . $script
		);
		if ( false === $script_written ) {
			unlink( $script_file );
			$this->fail( 'Could not write temporary install-functions test script.' );
		}

		$descriptor_spec = array(
			0 => array( 'pipe', 'r' ),
			1 => array( 'pipe', 'w' ),
			2 => array( 'pipe', 'w' ),
		);
		$process         = proc_open(
			escapeshellarg( PHP_BINARY ) . ' ' . escapeshellarg( $script_file ),
			$descriptor_spec,
			$pipes,
			__DIR__
		);

		if ( ! is_resource( $process ) ) {
			unlink( $script_file );
			$this->fail( 'Could not start isolated install-functions test process.' );
		}

		fclose( $pipes[0] );
		$stdout = stream_get_contents( $pipes[1] );
		$stderr = stream_get_contents( $pipes[2] );
		fclose( $pipes[1] );
		fclose( $pipes[2] );
		$exitcode = proc_close( $process );
		unlink( $script_file );

		$this->assertSame(
			0,
			$exitcode,
			"Isolated install-functions script failed.\nSTDOUT:\n" . $stdout . "\nSTDERR:\n" . $stderr
		);

		$decoded = json_decode( $stdout, true );
		$this->assertIsArray(
			$decoded,
			"Isolated install-functions script did not return JSON.\nSTDOUT:\n" . $stdout . "\nSTDERR:\n" . $stderr
		);

		return $decoded;
	}

	/**
	 * Gets helper code prepended to every isolated script.
	 *
	 * @return string PHP script body.
	 */
	private function get_isolated_script_prelude(): string {
		return <<<'PHP'
function wp_pg_install_test_respond( array $payload ) {
	echo json_encode( $payload );
}

function wp_pg_install_test_remove_tree( $path ) {
	if ( ! is_dir( $path ) ) {
		return;
	}

	$iterator = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator( $path, FilesystemIterator::SKIP_DOTS ),
		RecursiveIteratorIterator::CHILD_FIRST
	);

	foreach ( $iterator as $item ) {
		if ( $item->isDir() ) {
			rmdir( $item->getPathname() );
		} else {
			unlink( $item->getPathname() );
		}
	}

	rmdir( $path );
}
PHP;
	}
}
